/**
 * Creates testFns.customerTestData for testing
 *
 * Generated by hand per the following procedure (total time: 15 minutes)
 * - set a breakpoint in the real app just after customers were loaded
 * - execute the following line in the console:
 *      manager.exportEntities(null, false); // excludes metadata
 * - scrape the console window and paste into http://jsonprettyprint.com/
 * - OR use SublimeText PrettyJSON plug in which I did
 * - paste from there to here
 *
 * This method is copied from the breeze.js zza-node-mongodb sample
 */

(function (testFns) {
    var customerTestData = {
        "tempKeys": [],
        "entityGroupMap": {
            "Customer:#SiqCloset.Model": {
                "entities": [
                    {
                        "customerID": "809930f8-3c1e-4943-b5e9-9f6d258f730d",
                        "name": "Ade Johansyah",
                        "address": "Jl. H. Samali Ujung no 30A - Pejaten - Jakarta Selatan 12510",
                        "phoneNo": "0812 882 8828",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "f24d75a6-c396-4400-a49c-f171975e598e",
                        "name": "Adela Martha Sutanto",
                        "address": "Permata Puri Media Blok C2 No 7 - Kembangan - Jakarta Barat 11610. ",
                        "phoneNo": "5835-0033 / 0818 0601 2401",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "105e56c4-b4e7-4b05-85c7-3624a693eec6",
                        "name": "Adeline Naomi",
                        "address": "Komp. Wika Blok BR4/15 - Balikpapan ",
                        "phoneNo": "0542 7150001",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "93ffdc46-1c9b-48d9-96a4-5459cd5139f0",
                        "name": "Adeline Suhadi",
                        "address": "Vila bukit regency 2 PD 4 no 8 - Surabaya",
                        "phoneNo": "0818 541000",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "e9af07ed-3a6f-4f5a-aed0-0e89d867ff9d",
                        "name": "Afifah Andi",
                        "address": "Cendrawasih 4 no 42 - makassar 90124",
                        "phoneNo": "0819 4159 159",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "e2eb6cb9-a749-414b-a100-eca47b81590d",
                        "name": "Agna Wulan",
                        "address": " jl. Panjang no.44 -cidodol rt.004 rw.004 - kelurahan sukabumi selatan - jakarta barat",
                        "phoneNo": "0812 1212 3100",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "0e1f7463-e4fe-4274-8054-f9bddd39c631",
                        "name": "Agnes Kartika/Adela Martha",
                        "address": "Jl. Taman Elok no 87 - Lippo Karawaci Sentral - Tangerang ",
                        "phoneNo": "0815 1451 0016 ",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "e7894935-2972-4a99-b6e6-8c7c729c292b",
                        "name": "Agnez Brenda",
                        "address": "Apartment kedoya elok unit N 603 - Jl. Panjang raya no 1 - Jak-Bar",
                        "phoneNo": "0813 1089 6999",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "81c33b88-6d8f-41b2-8736-f603a9d79b1d",
                        "name": "Agustina Hadiwidjaja",
                        "address": "Taman Permata Buana Blok A3/2 - Jl. Pulau Tidung 10 - Jakarta Barat 11610",
                        "phoneNo": "0816-136 8604",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "ee1dd1bf-b5fe-4614-aefa-cfaf280bef07",
                        "name": "Albert Sugiharta",
                        "address": "Gang Suniaraja 33 - Bandung",
                        "phoneNo": "0812 3628 9198",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "58a82fb9-4b4d-4551-896a-86d7b3cfd2b5",
                        "name": "Alexandra Leirissa",
                        "address": "Apartment The Essence Tower 1 #2603 - Jl. Darmawangsa X - Jakarta Selatan 12150",
                        "phoneNo": "0811 833 377",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "685a3225-82c4-46c1-94db-ff07b1da8e26",
                        "name": "Alice Natasya",
                        "address": "Jl. Bintan 9. Malang - Jawa Timur 65117",
                        "phoneNo": "0818 0380 5803",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "f0268e6e-b356-4b46-a572-094e877dcff4",
                        "name": "Allen Ten",
                        "address": "Jln. Wijaya Kusuma no. 37/39 - Kota Metro - Lampung 34111  ",
                        "phoneNo": "0725-48181/0811796917",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "fbfe7fcb-e438-4117-ba55-73fc2b7cad4e",
                        "name": "Almira Rosalie",
                        "address": "jl. Kebon kacang raya - Apartemen Thamrin Residences - Tower Alamanda unit 05AA - Jakarta Pusat",
                        "phoneNo": "0812 8423 3377",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "395925a7-9368-4a8f-a1fb-e51a24c58094",
                        "name": "Amanda Wibowo",
                        "address": "Jl. Dharmahusada Utara 4 No. 22 - Surabaya 60285",
                        "phoneNo": "0855 300 8899 / 031 593 2929",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "504f724d-7b4e-426f-b602-5cf2cd0daf19",
                        "name": "Ambarwati Soemarsono",
                        "address": "Jl. Pinang Mas III Blok UU NO 6 -  Jakarta Selatan 12310",
                        "phoneNo": "0815 1319 6899",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "56eac363-3ff2-43bd-b278-954442832672",
                        "name": "Anandi Situmorang",
                        "address": "Jl. Tebet Dalam III C no 2 - Tebet - Jakarta Selatan 12180",
                        "phoneNo": "0821 1020 7006",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "045fa45e-45f4-4e82-96f6-8ae5c1c568b3",
                        "name": "Anastasia Anny",
                        "address": "Poris Paradise 3, Blok BA.7 no.9 - Cipondoh Tangerang",
                        "phoneNo": "0856 855 6709",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "782f9445-0a2c-4ba6-a0d4-76833d1a3ef6",
                        "name": "Anastasia Kristiani",
                        "address": "Jln. Pelangi kuning 4 blok B7U no.8 - perum gading residence - Jakarta utara 14250",
                        "phoneNo": "0856 9897 000",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    },
                    {
                        "customerID": "99dcd778-065c-492a-b872-1c29da696bd4",
                        "name": "Anastasia Ng",
                        "address": "Damar Golf Raya 33 - Bukit Golf Mediterania. Pantai Indah Kapuk - Jakarta Utara 14470",
                        "phoneNo": "5694 8080/0812 952 8813",
                        "entityAspect": {
                            "entityState": "Unchanged"
                        }
                    }
                ]
            }
        },
        "metadataVersion": "1.0.5"
    };

    testFns.customerTestData = JSON.stringify(customerTestData);

})(window.testFns);

